---
- name: Ensure json config file is in place and is valid
  template:
    src: "amazon-cloudwatch-agent.json.j2"
    dest: "{{ cwa_config_dir }}/amazon-cloudwatch-agent.d/fragment_{{ cfg_index }}"
    owner: root
    group: root
    mode: 0644
  notify: restart cwa
  loop: "{{cwa_config_maps}}"
  loop_control:
    index_var: cfg_index

- name: Ensure service is started and enabled
  service:
    name: amazon-cloudwatch-agent
    state: "{{ cwa_service_state }}"
    enabled: "{{ cwa_service_enabled }}"

- name: Configure log rotation
  copy:
    dest: /etc/logrotate.d/cloudwatch-agent
    owner: root
    group: root
    mode: 0644
    content: |
      # Ansible managed

      {{ cwa_logfile }} {
        size 50M
        rotate 8
        compress
        copytruncate
        missingok
      }
